module.exports =

[{
	name: "web",
	repo: "https://github.com/bxtx999/web.git",
	version: "master"
}, {
	name: "real-time",
	repo: "https://github.com/overleaf/real-time.git",
	version: "master"
}, {
	name: "document-updater",
	repo: "https://github.com/overleaf/document-updater.git",
	version: "master"
}, {
	name: "clsi",
	repo: "https://github.com/overleaf/clsi.git",
	version: "master"
}, {
	name: "filestore",
	repo: "https://github.com/overleaf/filestore.git",
	version: "master"
}, {
	name: "track-changes",
	repo: "https://github.com/overleaf/track-changes.git",
	version: "master"
}, {
	name: "docstore",
	repo: "https://github.com/overleaf/docstore.git",
	version: "master"
}, {
	name: "chat",
	repo: "https://github.com/overleaf/chat.git",
	version: "master"
}, {
	name: "spelling",
	repo: "https://github.com/overleaf/spelling.git",
	version: "master"
}, {
	name: "contacts",
	repo: "https://github.com/overleaf/contacts.git",
	version: "master"
}, {
	name: "notifications",
	repo: "https://github.com/overleaf/notifications.git",
	version: "master"
}]
